---
- name: copy aliases
  become: yes
  become_user: "{{ username }}"
  copy:
    src: "{{ aliases_path }}"
    dest: ~/.bash_aliases

- name: update .zshrc - source aliases
  become: yes
  become_user: "{{ username }}"
  lineinfile:
    path: ~/.zshrc
    line: 'source $HOME/.bash_aliases'

- name: install zsh autosuggestions
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: update .zshrc plugins
  become: yes
  become_user: "{{ username }}"
  lineinfile:
    path: ~/.zshrc
    regexp: '^plugins=\('
    line: 'plugins=(git zsh-autosuggestions)'

- name: install zsh syntax highlighting
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: update .zshrc plugins
  become: yes
  become_user: "{{ username }}"
  lineinfile:
    path: ~/.zshrc
    regexp: '^plugins=\('
    line: 'plugins=(git zsh-autosuggestions zsh-syntax-highlighting)'
