---
- name: "add user: {{ username }}"
  become: yes
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    groups:
      - sudo
      - docker
    state: present

- name: add public key
  authorized_key:
    user: "{{ username }}"
    key: "{{ public_key }}"

- name: apt update
  apt:
    update_cache: true

- name: install dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - aptitude
    - tmux
    - htop
