---
- name: install pip3
  become: yes
  apt:
    name: python3-pip
    update_cache: yes

- name: install aws cli
  become: yes
  become_user: "{{ username }}"
  pip:
    name: awscli
    extra_args: --upgrade --user

- name: add ~/.local/bin to $PATH
  become: yes
  become_user: "{{ username }}"
  lineinfile:
    path: ~/.zshrc
    line: export PATH=~/.local/bin:$PATH
