- name: Check if spacevim exists
  become: yes
  become_user: "{{ username }}"
  stat:
    path: ~/.SpaceVim
  register: spacevim

- name: download, install SpaceVim
  become: yes
  become_user: "{{ username }}"
  when: spacevim.stat.exists == False
  block:
    - name: Download SpaceVim
      get_url: url=https://spacevim.org/install.sh dest=/tmp/spacevim-installer.sh mode=0755

    - name: Execute the spacevim-installer.sh
      shell: /tmp/spacevim-installer.sh

    - name: Remove the spacevim-installer.sh
      file: path=/tmp/spacevim-installer.sh state=absent

    - name: set git default editor to vim
      shell: git config --global core.editor "vim"
