---
- hosts: devi
  roles:
    - common

#   roles:
#     - role: gantsign.oh-my-zsh
#       users:
#         - username: hancock

#   tasks:
#     - name: switch to dev user
#       become: yes
#       become_user: hancock
#       block:
#       - name: nvm
#         shell: >
#           curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
#         args:
#           creates: "/home/hancock/.nvm/nvm.sh"
#       - name: update .zshrc with nvm settings
#         blockinfile:
#           path: /home/hancock/.zshrc
#           block: |
#             export NVM_DIR="$HOME/.nvm"
#             [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#             [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
